version: '3'

services:
  user-management-service:
    build:
      context: ./UserManagmentService.API  # Point to the folder where your Dockerfile is located
      dockerfile: Dockerfile  # Optional: This is the default if the Dockerfile is named 'Dockerfile'
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "user_db"
      DB_PORT: "5432"
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_NAME: "userservice"
      JWT_SECRET: "your_jwt_secret_key_here" # You can add any other environment variables if needed
    depends_on:
      - user_db

  user_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userservice
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  training-sessio-management-service:
    build:
      context: ./TrainingSessionManagementService.API  # Point to the folder where your Dockerfile is located
      dockerfile: Dockerfile  # Optional: This is the default if the Dockerfile is named 'Dockerfile'
    ports:
      - "3001:3001"
    environment:
      DB_HOST: "session_db"
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_NAME: "trainingsessionservice"
      JWT_SECRET: "your_jwt_secret_key_here" # You can add any other environment variables if needed
    depends_on:
      - session_db
  session_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trainingsessionservice
    ports:
      - "5433:5432"
    volumes:
      - session_db_data:/var/lib/postgresql/data  

volumes:
  db_data:
    driver: local
  session_db_data:
    driver: local
