version: '3'

services:
  user-management-service:
    build:
      context: ./UserManagmentService.API
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "user_db"
      DB_PORT: "5432"
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_NAME: "userservice"
      JWT_SECRET: "your_jwt_secret_key_here"
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - my_custom_network

  user_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userservice
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_custom_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      retries: 5
      timeout: 5s

  training-session-management-service:
    build:
      context: ./TrainingSessionManagementService.API
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_HOST: "session_db"
      DB_PORT: "5432"
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_NAME: "trainingsessionservice"
      JWT_SECRET: "your_jwt_secret_key_here"
    depends_on:
      session_db:
        condition: service_healthy
    networks:
      - my_custom_network

  session_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trainingsessionservice
    ports:
      - "5433:5432"
    volumes:
      - session_db_data:/var/lib/postgresql/data
    networks:
      - my_custom_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      retries: 5
      timeout: 5s

  workout-recommendation-service:
    build:
      context: ./WorkOutRecommdationService.API
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - GROQ_API_KEY=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
    networks:
      - my_custom_network

volumes:
  db_data:
    driver: local
  session_db_data:
    driver: local

networks:
  my_custom_network:
    driver: bridge
