import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TimelineModule } from 'primeng/timeline';
import { CardModule } from 'primeng/card';

interface EventItem {
  status?: string;
  date?: string;
  icon?: string;
  color?: string;
  image?: string;
  content?: string;
}

@Component({
  selector: 'app-timeline',
  standalone: true,
  imports: [CommonModule, TimelineModule, CardModule],
  templateUrl: './timeline.component.html',
  styleUrls: ['./timeline.component.scss'],
})
export class TimelineComponent {
  events: EventItem[];

  constructor() {
    this.events = [
      {
        status: 'Personal Training Session',
        date: 'Daily',
        icon: 'pi pi-user',
        color: '#4CAF50',
        content: `1-on-1 Training Session with Coachs
          Focus: Upper Body Strength
          Equipment: Free Weights, Resistance Bands
          Duration: 60 minutes`,
      },
      {
        status: 'Nutrition Plan Updated',
        date: 'Weekly',
        icon: 'pi pi-apple',
        color: '#FF9800',
        content: `Weekly Meal Plan Generated by AI tailored to your goals
          AI will generate a meal plan based on your goals and preferences
          `,
      },
      {
        status: 'Group Fitness Class',
        date: '3 Hr 15 Min 365 days',
        icon: 'pi pi-users',
        color: '#2196F3',
        content: `HIIT Circuit Training
          Participants: 12/15
          Intensity Level: Advanced
          Calories Burned: 550
          Group Achievement: 98% Target HR Zone`,
      },
      {
        status: 'Progress Assessment',
        date: 'Daily',
        icon: 'pi pi-chart-bar',
        color: '#673AB7',
        content: `Monthly Progress Review
          Weight: -2.5kg from last month
          Muscle Mass: +1.2kg
          Body Fat: -1.8%
          Next Goal Setting Session: Tomorrow`,
      },
      {
        status: 'Recovery & Wellness',
        date: '',
        icon: 'pi pi-heart',
        color: '#E91E63',
        content: `Evening Wellness Session
          30min Guided Meditation
          Mobility Work Completed
          Sleep Schedule Optimized
          Recovery Score: 8.5/10`,
      },
      {
        status: 'Community Challenge',
        date: 'once a week',
        icon: 'pi pi-flag',
        color: '#00BCD4',
        content: `October Fitness Challenge
          Current Rank: 5th of 234
          Points Earned Today: 850
          Streak: 12 days
          Team Progress: 89% to Goal`,
      },
    ];
  }
}
