name: Build Profile UI Service

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag"
        required: true
        default: "latest"

jobs:
  build-profile-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Profile UI Service
        uses: docker/build-push-action@v4
        with:
          context: ./UiLayer
          file: ./UiLayer/Dockerfile.profile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/profile-service:${{ github.event.inputs.tag }}
