name: Build Workout Recommendation Service

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag"
        required: true
        default: "latest"

jobs:
  build-workout-recommendation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Workout-Recommendation Service
        uses: docker/build-push-action@v4
        with:
          context: ./WorkOutRecommdationService.API
          file: ./WorkOutRecommdationService.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/workout-recommendation-service:${{ github.event.inputs.tag }}
